### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by johnforeland** [navikt/crm-arbeidsgiver-base#246]
### Commands

/deploy [org] [package id]
/promote [package id] [your_name] [description]

### Examples

- /deploy prod 04t2o000001MxwsAAC
- /deploy preprod 04t2o000001MxwsAAC
- /promote 04t2o000001MxwsAAC johnforeland Implemented feature X

### Status Emojis

- 👀 Starting
- 🚀 Working
- 🎉 Success
- 👎 Failure

### Error Log

See the log on the Actions tab GitHub.

**Comment by suddal** [comment]
/promote 04t2o000001MxyZAAS suddal "Assigned flexipages to temporary layoff app"

**Comment by gstenseng** [comment]
/promote 04t2o000001MxzIAAS Gisle "Changed translation on Ingen personsensitive opplysninger"

**Comment by gstenseng** [comment]
/deploy prod /deploy preprod 04t2o000001My2MAAS Gisle Stenseng

**Comment by gstenseng** [comment]
/ promote 04t2o000001My6EAAS Gisle Stenseng

**Comment by johnforeland** [comment]
/promote 04t2o000001My8eAAC johnforeland Changed process to trigger for sending emails
